### ISSUE TITLE
Runtime error while running locoGP.java

### ISSUE THREAD

**Issue by khalibartan** [codykenb/locoGP#1]
@codykenb I was trying to run locoGP.java using eclipse java EE IDE and openjdk-8-djk. Here is the error that I got.
```
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 254
Exception Details:
  Location:
    Sort1ProblemTest.sort([Ljava/lang/Integer;Ljava/lang/Integer;)[Ljava/lang/Integer; @93: if_icmpge
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 121b 57b8 0021 c43a fffe 1400 22c4 37ff
    0x0000010: fcb8 0029 c437 fffc bb00 2b59 b700 2cc4
    0x0000020: 3aff fbbb 002b 59b7 002c c43a fffa 1400
    0x0000030: 22c4 37ff f814 0022 c437 fff6 c419 fffb
    0x0000040: 122d b800 03b6 0031 5703 3dc4 19ff fb12
    0x0000050: 32b8 0003 b600 3157 1c2b b600 02a2 00a1
    0x0000060: c419 fffb 1233 b800 03b6 0031 5703 3ec4
    0x0000070: 19ff fb12 34b8 0003 b600 3157 1d2b b600
    0x0000080: 0204 64a2 0068 c419 fffb 1235 b800 03b6
    0x0000090: 0031 572a 1d32 b600 022a 1d04 6032 b600
    0x00000a0: 02a4 0037 c419 fffb 1236 b800 03b6 0031
    0x00000b0: 572a 1d32 b600 0236 04c4 19ff fb12 37b8
    0x00000c0: 0003 b600 3157 2a1d 2a1d 0460 3253 2a1d
    0x00000d0: 0460 1504 b800 0353 c419 fffb 1238 b800
    0x00000e0: 03b6 0031 5784 0301 a7ff 87c4 19ff fb12
    0x00000f0: 39b8 0003 b600 3157 8402 01a7 ff50 c419
    0x0000100: fffb 123a b800 03b6 0031 572a b800 40bb
    0x0000110: 0042 59c4 16ff fc12 4401 0101 0101 c419
    0x0000120: fffe 0103 1001 b700 4759 c419 fffb b500
    0x0000130: 4b59 c419 fffa b500 4ebb 002b 59b7 002c
    0x0000140: c43a fffa 5912 50b8 0054 b500 58b6 005c
    0x0000150: 57b0                                   
  Stackmap Table:
    append_frame(@88,Integer)
    append_frame(@124,Integer)
    same_frame_extended(@229)
    chop_frame(@248,1)
    chop_frame(@267,1)

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at de.uka.ipd.sdq.ByCounter.execution.MethodInvocationHelper.callMethods(MethodInvocationHelper.java:65)
	at de.uka.ipd.sdq.ByCounter.execution.BytecodeCounter.execute(BytecodeCounter.java:243)
	at de.uka.ipd.sdq.ByCounter.execution.BytecodeCounter.execute(BytecodeCounter.java:190)
	at locoGP.fitness.OpCodeCounter.run(OpCodeCounter.java:58)
	at locoGP.fitness.RunFitnessFunction.runBasicCounter(RunFitnessFunction.java:25)
	at locoGP.fitness.IndividualEvaluator.evaluateNoTimeLimit(IndividualEvaluator.java:46)
	at locoGP.fitness.IndividualEvaluator.evaluateIndNoTimeLimit(IndividualEvaluator.java:37)
	at locoGP.Generation.createGenfromRandomMutation(Generation.java:452)
	at locoGP.Generation.<init>(Generation.java:134)
	at locoGP.locoGP.createFirstGeneration(locoGP.java:70)
	at locoGP.locoGP.realMain(locoGP.java:96)
	at locoGP.locoGP.main(locoGP.java:33)
```
I'm not able to understand the error. Could you tell me how can I fix this error. Anyways I want to run locoGP with fitness metric a run-time rather than opcode counts. What changes should I need to make for that.

**Comment by khalibartan** [comment]
@codykenb When I updated the code in RunFitnessFunction.java file to use run time instead I got following error 
```
java.lang.IllegalStateException: Seed fitness is not 1
```

**Comment by codykenb** [comment]
Hi, for the first issue, only Java 6 or 7 with -noverify work. (As shown in README.txt)

Java 7 & 8 introduced more strict bytecode verification. locoGP uses the bycounter library to instrument the bytecode of mutated code, so although the bytecode still runs, it will not pass the verification process. Ideally ByCounter would be upgraded to create bytecode that will pass the verification process in Java 7 & 8.

[Runtimer](https://github.com/codykenb/locoGP/blob/master/locoGP_eclipse/src/locoGP/fitness/RunTimer.java) is older code which measures execution time. locoGP is designed so that the initial seed program gets a fitness value of 1. If the [seed fitness is not 1](https://github.com/codykenb/locoGP/blob/3b6dbfaa8aecaf3c564271cbc18d78ab4c8227dc/locoGP_eclipse/src/locoGP/Generation.java#L468), locoGP terminates.  This assumes the initial seed program has no errors, and the measure of it's running time is a benchmark which is to be improved upon. The running time of another program is divided by this initial measure. So if a mutated program is faster than the seed, it gets fitness less than one. See [getTimeFitnessRatio](https://github.com/codykenb/locoGP/blob/master/locoGP_eclipse/src/locoGP/individual/Individual.java#L223) for how the time component of fitness is calculated. Runtimer may need to be modified, so that the resulting fitness of the seed is 1 (the system will run if you remove the check for seed fitness=1, but I'm not sure how this would effect the fitness measures overall) .
